server:
  port: 8083

spring:
  application:
    name: scoring-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: mockanytime
      auto-index-creation: true
  ai:
    openai:
      base-url: ${GROQ_BASE_URL:https://api.groq.com/openai}
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama-3.3-70b-versatile

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always



